### ISSUE TITLE
Should isolate merge dependencies?

### ISSUE THREAD

**Issue by mparpaillon** [0x80/mono-ts#10]
Hey! Kudos for this repo. It helped me a ton. 

I'm using the noExternal option to include everything in my final bundle but there's a problem.

## Scenario A: I keep @repo/common in my package.json dependencies

Everything works but it isolate the @repo/common for nothing since everything is already in the final bundle thanks to noExternal

## Scenario B: I remove the @repo/common from package.json dependencies 

That way the isolate only has the final bundle and its package.json BUT it doesn't work but the @repo/common dependencies are not merged with the bundle package.json

So, for now I'll keep the @repo/common dependency in my package.json but I shouldn't have to right?

**Comment by 0x80** [comment]
I think using noExternal goes against what isolate-package is for. The main point of the isolate extraction is that you can treat your internal dependencies like regular NPM installed dependencies have their dependencies installed according to their manifest.

**Comment by mparpaillon** [comment]
Oh since you were using it in your example I took it as an valid option. Thanks for the response

**Comment by mparpaillon** [comment]
I got it working without the noExternal. Your repo and article helped me a lot this week. Thanks

**Comment by 0x80** [comment]
I realized there was a problem with the common package strategy. If you're still using that pattern you might want to read this https://github.com/0x80/mono-ts/commit/d0186fea48d41667203b5bd46addcde84033c0b3
